### ISSUE TITLE
Add exit to systray

### ISSUE THREAD

**Issue by GamzeeRakoon** [tobagin/whakarere#1]

**Comment by tobagin** [comment]
I’m actually in the process of re-writing the whole script using only native Gtk4/Libadwaita widgets instead of a webview, but I’m not planning to add a systray to it, I’m going to let gnome add it to the background apps like it’s intended, notification will likely be system notifications and badge on the icon if added to the the dash in the overview, which in turn should work in case extensions like dash to dock/dash to panel is used.

**Comment by tobagin** [comment]
I’m actually in the process of re-writing the whole script using only native Gtk4/Libadwaita widgets instead of a webview, but I’m not planning to add a systray to it, I’m going to let gnome add it to the background apps like it’s intended, notification will likely be system notifications and badge on the icon if added to the the dash in the overview, which in turn should work in case extensions like dash to dock/dash to panel is used.
